providers:
    - "https://api.fastly.com/public-ip-list"
    - "https://www.cloudflare.com/ips-v4"
    - "https://d7uri8nf7uskq.cloudfront.net/tools/list-cloudfront-ips"
    - "https://support.maxcdn.com/hc/en-us/article_attachments/360051920551/maxcdn_ips.txt"
    - "https://cachefly.cachefly.net/ips/rproxy.txt"
    - "https://docs-be.imperva.com/api/bundle/z-kb-articles-km/page/c85245b7.html"
    - "http://edge.sotoon.ir/ip-list.json"
    - "https://docs.oracle.com/en-us/iaas/tools/public_ip_ranges.json"
    - "https://raw.githubusercontent.com/m333rl1n/cdnx/main/static-CIDRs.txt"
    - "https://my.incapsula.com/api/integration/v1/ips"

# default interval is every 48h
interval: 48

resolvers:
    # Cloudflare
    - "1.1.1.1:53"
    - "1.0.0.1:53"
    # Google
    - "8.8.8.8:53"
    - "8.8.4.4:53"
    # Quad9
    - "9.9.9.9:53"
    - "149.112.112.112:53"
    # OpenDNS
    - "208.67.222.222:53"
    - "208.67.220.220:53"
    # Verisign
    - "64.6.64.6:53"
    - "64.6.65.6:53"
    # UncensoredDNS
    - "91.239.100.100:53"
    - "89.233.43.71:53"
    # dns.watch
    - "84.200.69.80:53"
    - "84.200.70.40:53"